### ISSUE TITLE
reconfigure existing config resets sync_racestart

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#45]
If I use to option **-c nameconfigfile.json** the value for sync_racestart resets to 0.0

```
    "sync_racestart": 0.0,
    "video_cache": null,
    "video_gaptime": null,
    "video_skipend": 3231.94,
    "video_skipstart": 45.0,
    "video_threshold": null
```

**Comment by Michel-NL** [comment]
sync_racestart resets also with **-t** option

**Comment by SenorPez** [comment]
Should be fixed for the `-c` option, which was resetting it every time you edited the file.

It seems to be working as intended for the `-t` option. If you change the start clipping, it's reset to 0. If you change the end clipping, it's not changed at all.

After removing blackframe detection, I considered making an adjustment such that any change in the start clipping would be mirrored into the telemetry sync value. (For example, if you subtract 4 from the start clipping, it would subtract 4 from the telemetry sync value.) This would, in theory, keep the telemetry in sync even if changing the start clipping.

I decided against it because of the already intuitive nature of this value. It's much easier to have it go to zero, run the video to get the offset, and reset it.

**Comment by Michel-NL** [comment]
-c option is fixed...thnxs
