### ISSUE TITLE
Champion screen

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#46]
Enhancements :)

We race about 16 races. Not every player races every race. So the champion screen and the series points is not complete if a player did not play that particular race.
Is it possible to put the player names with previous series points in the config so they appear in the champion screen?

**Comment by Michel-NL** [comment]
I was thinking what do you wanted with the last screen where its saying **Champion** **Runner Up**
You think that people are merging the video's of different races into one large video?
Never thought about that...I think i'm not going to use that because it will be a +10 hours video.
Is it possible to make that screen an option to use? If you use 1 race in the video that it has no use...or not?

**Comment by SenorPez** [comment]
Regarding the first comment: Yes, that's 100% something I'm planning on adding, for that exact reason. I just need to think through how best to do it so that it doesn't break the actual telemetry processing.

For the second comment: I really intend for the Champion card to only be shown when you finish a Championship, not at the end of each race. And it can live in an independent video. For example, in my 0.2 test video series, it's only displayed at the end of the last race of the Championship: [https://www.youtube.com/watch?v=9_m5Gc_w0JE&list=PLy-S2xlLES80Wy18ydpmO1D9jU200jcWJ&index=16](https://www.youtube.com/watch?v=9_m5Gc_w0JE&list=PLy-S2xlLES80Wy18ydpmO1D9jU200jcWJ&index=16)

For most races, I'd think the Champion screen wouldn't be included. That's why it defaults to "N" in the configuration option to include it.

**Comment by SenorPez** [comment]
Now has support for "additional participants." These are participants who have points in a series but are not racing in the current race. They will be added to the Series Standing list (earning 0 points for the current race) and sorted in. They are not currently used anywhere else.
